name: Ping Vercel Cron

on:
  schedule:
    - cron: "0 10 * * *"   # 10h UTC
    - cron: "0 13 * * *"   # 13h UTC
    - cron: "0 14 * * *"   # 14h UTC
    - cron: "0 16 * * *"   # 16h UTC
    - cron: "0 19 * * *"   # 19h UTC
    - cron: "0 21 * * *"   # 21h UTC
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Debug CRON_URL
        env:
          URL: ${{ secrets.CRON_URL }}
        run: |
          echo "🔎 Debugging CRON_URL"
          echo "len=$(printf '%s' "$URL" | wc -c)"
          printf '%s' "$URL" | hexdump -C

      - name: Call /api/cron
        env:
          URL: ${{ secrets.CRON_URL }}
          SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          set -e
          if [ -z "$URL" ]; then
            echo "❌ CRON_URL secret is missing"; exit 1
          fi
          echo "Calling $URL ..."
          CODE=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -H "Authorization: Bearer $SECRET" \
            "$URL" || true)
          echo "HTTP $CODE"
          if [ -f /tmp/resp.json ]; then
            cat /tmp/resp.json || true
          else
            echo "No response file; curl failed before request."
          fi
          test "$CODE" -lt 400
