name: Ping Vercel Cron

on:
  schedule:
    - cron: "0 10 * * *" # 10h UTC
    - cron: "0 13 * * *" # 13h UTC
    - cron: "0 14 * * *" # 14h UTC
    - cron: "0 16 * * *" # 16h UTC
    - cron: "0 19 * * *" # 19h UTC
    - cron: "0 21 * * *" # 21h UTC
  workflow_dispatch: {} # lancer manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron
        env:
          URL: ${{ secrets.CRON_URL }}
          SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          echo "Calling $URL ..."
          CODE=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
            -H "Authorization: Bearer $SECRET" \
            "$URL")
          echo "HTTP $CODE"
          cat /tmp/resp.json || true
          test "$CODE" -lt 400
