jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron
        env:
          URL: ${{ secrets.CRON_URL }}
          SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          set -e
          if [ -z "$URL" ]; then
            echo "❌ CRON_URL secret is empty or missing."
            exit 1
          fi
          echo "Calling endpoint..."
          for i in 1 2 3; do
            CODE=$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
              -H "Authorization: Bearer $SECRET" \
              "$URL" || true)
            echo "HTTP $CODE"
            cat /tmp/resp.json || true
            if [ "$CODE" -lt 400 ]; then
              echo "✅ Success"
              exit 0
            fi
            echo "Retry $i/3 in 10s..."
            sleep 10
          done
          echo "❌ Failed after retries"
          exit 1
